# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Welcome_plc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 379)
        MainWindow.setStyleSheet("background-color: rgb(20, 20, 20);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/* Set background colors and properties */\n"
"QFrame#mainFrame{\n"
"background-color: #f0f0f0;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QFrame#contentFrame{\n"
"background-color: #fff;\n"
"}\n"
"\n"
"QFrame#leftMenuFrame{\n"
"background-color: #36647b;\n"
"}\n"
"\n"
"QWidget#page_License {\n"
"background-color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"color:rgb(255, 166, 0);\n"
"background-color: rgb(88, 88, 88);\n"
"}\n"
"QCheckBox{\n"
"font:  \"Poppins\";\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"color: #D7DBEC;\n"
"}\n"
"\n"
"/* Global styles for buttons */\n"
"QPushButton{\n"
"/*background-color: #383838;*/\n"
"border-radius: 5px;\n"
"border:2px solid #D7DBEC;;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"background:#2f373d; \n"
"/*font-family: Noto Sans;*/\n"
"font: 75 10pt \"Poppins\";\n"
"color: #fff;\n"
"height:40px;\n"
"width:150px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 166, 0);\n"
"}\n"
"\n"
"/* Styles for Tab Widgets */\n"
"QTabWidget::pane {\n"
"border:1px solid lightgray;\n"
"/*background: rgb(245, 245, 245);*/\n"
"\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"/*background: rgb(230, 230, 230);*/ \n"
"background-color: #191C24;\n"
"color:#F1F1F2;\n"
"border: 1px solid lightgray; \n"
"padding: 10px 30px 10px 30px;\n"
"margin:1px;\n"
"} \n"
"QTabBar::tab:hover {\n"
"    background-color:#343434;\n"
"    border-top-left-radius: 5px; \n"
"    border-top-right-radius: 5px; \n"
"    border-bottom-left-radius: 0px; \n"
"    border-bottom-right-radius: 0px; \n"
"} \n"
"\n"
"QTabBar::tab:selected {\n"
"    background: rgb(88,88,88);\n"
"    color:rgb(255, 166, 0);\n"
"    margin-bottom: -1px; \n"
"}\n"
"\n"
"/* QLabel settings */\n"
"QLabel#SettingBg1{\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgba(40, 40, 40, 0.2);\n"
"}\n"
"\n"
"QLabel#SettingBg2{\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgba(40, 40, 40, 0.2);\n"
"}\n"
"\n"
"QLabel#SettingBg3{\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgba(40, 40, 40, 0.2);\n"
"}\n"
"\n"
"QLabel#SettingBg4{\n"
"font: 14pt \"Poppins\";\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color:  rgba(40, 40, 40, 0.2);\n"
"}\n"
"\n"
"QLabel {\n"
"font-size: 8pt;\n"
"font:75  \"Poppins\";\n"
"font-weight: bold;\n"
"color: #D7DBEC;\n"
"/*font-family: Noto Sans;*/\n"
"}\n"
"\n"
"/* Global combobox settings */\n"
"QComboBox{\n"
"text-align: center;\n"
"border-radius: 5px;\n"
"border:2px solid #D7DBEC;\n"
"color: #D7DBEC;\n"
"padding: 2px;\n"
"font-weight: bold;\n"
"font-size: 8pt;\n"
"height:40px;\n"
"width:150px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"border: 0px; /* This seems to replace the whole arrow of the combo box */\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    text-align: center;\n"
"    qproperty-alignment: AlignCenter;\n"
"    background-color: white; /* Background color */\n"
"    color: #F1F1F2; /* Text color */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"image: url(img/Arrows-Down-4-icon.png);\n"
"width: 10px;\n"
"height: 10px;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"color:rgb(255, 166, 0);\n"
"background-color:white;\n"
"/*border: 2px solid #252429;\n"
"color: #252429;*/\n"
"}\n"
"\n"
"QTableView{\n"
"color: rgb(31, 31, 31);\n"
"background-color: rgb(209, 209, 209);\n"
"}\n"
"\n"
"QHeaderView::section { \n"
"font: 75 10pt \"Poppins\";\n"
"color: white;\n"
"background-color:#989898; \n"
"}\n"
"\n"
"QDateTimeEdit{\n"
"background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTableView::item { \n"
"font: 75 12pt \"Poppins\";\n"
"color:white; \n"
"background:#2f373d; \n"
"font-weight:900; \n"
"}\n"
"QTableView::item:selected {\n"
"font: 75 12pt \"Poppins\"; \n"
"color:black; \n"
"background:#7cc8b9; \n"
"font-weight:900; \n"
"}\n"
"QTableView{\n"
"color: rgb(31, 31, 31);\n"
"background-color: rgb(25, 28, 36);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(25, 28, 36);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Poppins\";\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 39, 531, 301))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(120, 0, 271, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.btnConnectDb = QtWidgets.QPushButton(self.widget)
        self.btnConnectDb.setGeometry(QtCore.QRect(190, 90, 131, 61))
        self.btnConnectDb.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.btnConnectDb.setObjectName("btnConnectDb")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(140, 160, 291, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.connStatus = QtWidgets.QTextEdit(self.centralwidget)
        self.connStatus.setGeometry(QtCore.QRect(50, 260, 521, 71))
        self.connStatus.setObjectName("connStatus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 613, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome To PLC Data Log APK"))
        self.btnConnectDb.setText(_translate("MainWindow", "Connect DB"))
        self.label_2.setText(_translate("MainWindow", "Click on connect btn to log db"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
